### PR TITLE
SetupCommand

### PR DESCRIPTION
**Pull request by MineKing9534**
## Checklist

 - [x] Read [Contribution Guidelines](https://github.com/SlimeCloud/java-SlimeBot#-contributing) and [Style Guides](https://github.com/SlimeCloud/java-SlimeBot#-style-guide)
 - [x] Test the Code
 - [x] This PR is ready to review and merge

## Description
This PR adds a setup command, that configures that bot for the current guild step by step

## TODO
- [x] Guild default configuration
- [x] Fdmds
- [x] Spotify notification
- [x] Staff message

## Related Issue
#16

### CODE REVIEW

**Comment by MineKing9534** [comment]
When I tested this, everything worked as expected (apart from entity selecta keeping theory selection after switching to the next frame but that is a discord issue)

**Comment by MineKing9534** [comment]
Still works for me

**Comment by MineKing9534** [comment]
Do you get any exceptions?

**Comment by MineKing9534** [comment]
I found  the error. It is now fixed and should be working as expected.

**Review by MatitoDA — APPROVED** [review]

**Pull request merged**
