### PR TITLE
Add poll name display and PollEditCommand

### PR DESCRIPTION
**Pull request by MineKing9534**
## Checklist

 - [x] Read [Contribution Guidelines](https://github.com/SlimeCloud/java-SlimeBot#-contributing) and [Style Guides](https://github.com/SlimeCloud/java-SlimeBot#-style-guide)
 - [x] Test the Code
 - [x] This PR is ready to review and merge

## Description
Adds an option to display the names of participants and a menu for editing existing polls

## Todo
- [x] Show names
- [x] Edit
- [x] Edit options

## Migration
```sql
alter table polls add names boolean;
update polls set names = false;
```

### CODE REVIEW

**Review by MatitoDev — COMMENTED** [review]
is there no way to update the poll instant or add a save button? i don't really like this solution, where the poll only updates when someone votes.

**Comment by MineKing9534** [comment]
I could add a "update" button but I wouldn't update the messagr automatically on every change because it is a rather slow operatoon (because we don't store description etc for the poll we have to retrieve the messe to get this informationand then edit it with the new content)

**Comment by MatitoDev** [comment]
an update button would be nice if It's not too complicated for you :D

**Comment by MineKing9534** [comment]
Done

**Review by MatitoDev — APPROVED** [review]

**Pull request merged**
