### PR TITLE
Use Database

### PR DESCRIPTION
**Pull request by MineKing9534**
## Checklist
 - [x] Read [Contribution Guidelines](https://github.com/SlimeCloud/java-SlimeBot#contributing)
 - [x] This PR is ready to review and merge
 
 ## TODO
 - [x] Database setup
 - [x] Commands
 - [x] Reports
 - [x] Spotify
 - [x] Events
 - [x] Staff-Message
 - [x] Config-Command
 - [x] Test

## Description
Use PostgreSQL database for data storage instead of YAML files

## Related Issue
#9, #49, #5, #22

### CODE REVIEW

**Comment by MineKing9534** [comment]
The switch to the database is done. This is now only waiting for #47 to resolve conflicts and make it easier to build the config command.

**Comment by MineKing9534** [comment]
> > The switch to the database is done. This is now only waiting for #47 to resolve conflicts and make it easier to build the config command.
> 
> #47 is merged :)

Nice, I'm currently working on finishing this PR

**Comment by MineKing9534** [comment]
This also resolves #49 now

**Comment by MineKing9534** [comment]
@MatitoDA If you don't have a working PGSQL database running to test against currently, I can send you the credentials for the test DB I used via DC DM.

**Comment by MineKing9534** [comment]
Now also fixes #22

**Review by MatitoDA — APPROVED** [review]

**Pull request merged**
