### PR TITLE
Leaderboard

### PR DESCRIPTION
**Pull request by MineKing9534**
## Checklist

 - [x] Read [Contribution Guidelines](https://github.com/SlimeCloud/java-SlimeBot#-contributing) and [Style Guides](https://github.com/SlimeCloud/java-SlimeBot#-style-guide)
 - [x] Test the Code
 - [x] This PR is ready to review and merge

## Description
- [x] Fix font problem
- [x] Render Leaderboard image
- [x] Details menu

### CODE REVIEW

**Review by MatitoDev — CHANGES_REQUESTED** [review]
In the Leaderboard the XP-Bar is not correctly displayed
image

I like the idea with the RankCards in the Leaderboard, but I have the feeling it might look too chaotic.

**Comment by MineKing9534** [comment]
The bar is not supposed to display the xp on the leaderboard but the level in comparison to the others

**Comment by MineKing9534** [comment]
And I think the rank cards in the leaderboard look very nice if you don't have such ugly ones like your test account xD

**Comment by MatitoDev** [comment]
> The bar is not supposed to display the xp on the leaderboard but the level in comparison to the others

hmm ok, but i guess it could cause confusion, if you use the RankCards but the "XP-Bar" with a different meaning

> And I think the rank cards in the leaderboard look very nice if you don't have such ugly ones like your test account xD

we can try it xd

**Review by MatitoDev — APPROVED** [review]

**Review by MatitoDev — APPROVED** [review]

**Pull request merged**
